#!/usr/bin/env python3
"""
共享工具:驱动 `sim nav`、生成实验用的配置变体、解析 nav.csv。

V4 的实验(E1–E4)都是"改几个参数 → 跑 `sim nav` → 读 nav.csv"。这里集中放:

  - find_sim():优先 Release 的 sim(实验量大,且数值与 Debug 逐字节一致);
  - read_yaml_subset() / write_yaml_subset():只覆盖 config/*.yaml 用到的 YAML 子集
    (按缩进嵌套的映射 + 标量 + 行尾注释),不引入 PyYAML 依赖;
  - variant_configs():以 config/robot.yaml、config/nav.yaml 为底,只改实验关心的
    字段 —— 其余参数始终跟随仓库里的默认值,不在脚本里复制一份;
  - run_nav():跑一次 `sim nav --no-viz`,返回 nav.csv 的头部元数据;
  - read_nav_csv():头部元数据(dict)+ 数据(pandas.DataFrame);
  - polyline 几何:带符号横向误差(左正)与路径净空,与 C++ 的 project_onto /
    footprint_clearance 同一定义。

地图读取复用 scripts/v3/_mapio.py(与 C++ map_io 逐 cell 一致)。
"""

from __future__ import annotations

import gzip
import math
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
DATA_DIR = REPO / "data" / "v4"
RESULTS_DIR = REPO / "results" / "v4"

sys.path.insert(0, str(REPO / "scripts" / "v3"))
from _mapio import Grid, K_OCCUPIED, inflate, load_grid  # noqa: E402,F401

SIM_DT = 0.01


# ---- sim 可执行文件 -------------------------------------------------------------

def find_sim(prefer: str = "release") -> Path:
    """返回 sim 的路径:默认 Release(快),找不到回退 Debug。"""
    order = ["clang18-release", "clang18-debug"] if prefer == "release" else ["clang18-debug", "clang18-release"]
    for preset in order:
        candidate = REPO / "build" / preset / "sim"
        if candidate.exists():
            return candidate
    raise FileNotFoundError("sim not found; build first: cmake --build --preset build-release -j")


# ---- YAML 子集 ---------------------------------------------------------------

def _parse_scalar(text: str):
    low = text.lower()
    if low in ("true", "false"):
        return low == "true"
    try:
        return int(text)
    except ValueError:
        pass
    try:
        return float(text)
    except ValueError:
        return text


def read_yaml_subset(path: Path) -> dict:
    """读 config/*.yaml 用到的 YAML 子集:嵌套映射(2 空格缩进)+ 标量,忽略注释。"""
    root: dict = {}
    stack: list[tuple[int, dict]] = [(-1, root)]
    for raw in Path(path).read_text().splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        key, _, value = line.strip().partition(":")
        while stack[-1][0] >= indent:
            stack.pop()
        parent = stack[-1][1]
        if value.strip():
            parent[key] = _parse_scalar(value.strip())
        else:
            parent[key] = {}
            stack.append((indent, parent[key]))
    return root


def _format_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return repr(value)
    return str(value)


def write_yaml_subset(cfg: dict, path: Path, comment: str = "") -> Path:
    lines = [f"# {line}" for line in comment.splitlines()] if comment else []

    def emit(node: dict, indent: int) -> None:
        for key, value in node.items():
            if isinstance(value, dict):
                lines.append(" " * indent + f"{key}:")
                emit(value, indent + 2)
            else:
                lines.append(" " * indent + f"{key}: {_format_scalar(value)}")

    emit(cfg, 0)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path


def _merge(base: dict, overrides: dict) -> dict:
    out = {k: (dict(v) if isinstance(v, dict) else v) for k, v in base.items()}
    for key, value in overrides.items():
        if isinstance(value, dict):
            if key not in out or not isinstance(out[key], dict):
                raise KeyError(f"override section '{key}' does not exist in the base config")
            out[key] = _merge(out[key], value)
        else:
            out[key] = value
    return out


def variant_configs(name: str, robot: dict | None = None, nav: dict | None = None,
                    out_dir: Path | None = None) -> tuple[Path, Path]:
    """以仓库默认配置为底,写出只改了 overrides 的 robot / nav 变体,返回两个路径。

    例:variant_configs("ideal", robot={"actuator_time_constant": 0.0},
                         nav={"controller": {"control_frequency": 100.0}})
    """
    out_dir = Path(out_dir or DATA_DIR / "configs")
    base_robot = read_yaml_subset(REPO / "config" / "robot.yaml")
    base_nav = read_yaml_subset(REPO / "config" / "nav.yaml")
    robot_path = write_yaml_subset(_merge(base_robot, robot or {}), out_dir / f"robot_{name}.yaml",
                                   f"generated by scripts/v4 — variant '{name}' of config/robot.yaml")
    nav_path = write_yaml_subset(_merge(base_nav, nav or {}), out_dir / f"nav_{name}.yaml",
                                 f"generated by scripts/v4 — variant '{name}' of config/nav.yaml")
    return robot_path, nav_path


# 理论验证用的"理想底盘":无执行器滞后、限幅放宽到不起作用(对应 control_tests 的解析用例)。
IDEAL_ROBOT = {"actuator_time_constant": 0.0, "limits": {"max_linear_vel": 1.0, "max_angular_vel": 50.0}}


def classic_pp(lookahead: float, velocity: float) -> dict:
    """经典 Pure Pursuit:固定 L_d、不限速、不原地转向(controller 段的 overrides)。"""
    return {
        "desired_linear_vel": velocity,
        "use_velocity_scaled_lookahead": False,
        "lookahead_dist": lookahead,
        "use_curvature_regulation": False,
        "use_rotate_to_heading": False,
    }


def no_approach_slowdown(velocity: float) -> dict:
    """关掉接近目标减速(合成路径的实验只看转角 / 直线段,不看停车)。"""
    return {"approach_dist": 0.01, "min_approach_vel": velocity}


# ---- 路径文件 -------------------------------------------------------------------

def write_path_csv(points, path: Path, comment: str = "") -> Path:
    """写 `sim nav --path` 可读的折线(x,y 两列;朝向由 sim 按线段方向补)。"""
    lines = [f"# {comment}"] if comment else []
    lines.append("x,y")
    lines += [f"{x!r},{y!r}" for x, y in points]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path


# ---- 运行 sim nav ---------------------------------------------------------------

def parse_header(lines) -> dict:
    meta: dict = {}
    for line in lines:
        if not line.startswith("#"):
            break
        body = line[1:].strip()
        if "=" in body:
            key, value = body.split("=", 1)
            meta[key.strip()] = _parse_scalar(value.strip())
    return meta


def run_nav(sim: Path, out_csv: Path, *, map_yaml: str | None = None, path_csv: Path | None = None,
            start: str | None = None, goal: str | None = None, seed: int = 1, preset: str = "default",
            controller_input: str = "ekf", robot: Path | None = None, nav: Path | None = None,
            max_time: float | None = None) -> dict:
    """跑一次 `sim nav --no-viz`,返回 nav.csv 的头部元数据(status、误差、净空……)。"""
    cmd = [str(sim), "nav", "--no-viz", "--out", str(out_csv), "--seed", str(seed),
           "--preset", preset, "--controller-input", controller_input]
    if map_yaml is not None:
        cmd += ["--map", str(map_yaml)]
    if path_csv is not None:
        cmd += ["--path", str(path_csv)]
    if start is not None:
        cmd += ["--start", start]
    if goal is not None:
        cmd += ["--goal", goal]
    if robot is not None:
        cmd += ["--robot", str(robot)]
    if nav is not None:
        cmd += ["--nav", str(nav)]
    if max_time is not None:
        cmd += ["--max-time", repr(max_time)]
    Path(out_csv).parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"sim nav failed ({proc.returncode}):\n{' '.join(cmd)}\n{proc.stdout}{proc.stderr}")
    with open(out_csv) as f:
        return parse_header(f)


def read_nav_csv(path: Path) -> tuple[dict, pd.DataFrame]:
    """nav.csv(或 save_slim 写的 .csv.gz)→ (头部元数据, 数据表)。"""
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt") as f:
        meta = parse_header(f)
    df = pd.read_csv(path, comment="#")
    return meta, df


def run_and_load(sim: Path, out_csv: Path, keep: bool = False, **kwargs) -> tuple[dict, pd.DataFrame]:
    """run_nav + read_nav_csv;keep = False 时读完即删(全精度 nav.csv 每分钟约 6 MB)。"""
    run_nav(sim, out_csv, **kwargs)
    meta, df = read_nav_csv(out_csv)
    if not keep:
        Path(out_csv).unlink()
    return meta, df


# 分析脚本用到的列;save_slim 只存这些(7 位有效数字,gzip),体积约为原始 CSV 的 1/20。
SLIM_COLUMNS = ("t", "cmd_v", "cmd_w", "true_v", "true_w", "truth_x", "truth_y", "truth_yaw",
                "ekf_x", "ekf_y", "ekf_yaw", "ekf_sigma_xx", "ekf_sigma_yy", "ekf_sigma_xy",
                "ekf_sigma_thth", "nis_encoder", "nis_imu", "act_v", "act_w", "lookahead_x", "lookahead_y",
                "lookahead_dist", "curvature", "regime", "e_ctrl", "e_true", "e_est", "arclength", "clearance")


def save_slim(meta: dict, df: pd.DataFrame, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wt") as f:
        for key, value in meta.items():
            f.write(f"# {key} = {value}\n")
        df[list(SLIM_COLUMNS)].to_csv(f, index=False, float_format="%.7g")
    return path


def traveled(df: pd.DataFrame) -> np.ndarray:
    """真值走过的路程 s(t)(每行是推进前的快照,所以首行 s = 0)。"""
    step = np.hypot(np.diff(df["truth_x"].to_numpy()), np.diff(df["truth_y"].to_numpy()))
    return np.concatenate([[0.0], np.cumsum(step)])


# ---- 折线几何 -------------------------------------------------------------------

def signed_cross_track(points: np.ndarray, polyline: np.ndarray) -> np.ndarray:
    """点到折线的距离,按最近线段的左右定号(左正)。

    points: (N, 2);polyline: (M, 2)。最近点落在拐点上时,用相邻两段中较近的那段定号;
    对左转的转角,内侧(切角)为正,出弯后越到外侧为负。"""
    p = np.asarray(points, dtype=float)[:, None, :]
    a = np.asarray(polyline[:-1], dtype=float)[None, :, :]
    b = np.asarray(polyline[1:], dtype=float)[None, :, :]
    ab = b - a
    t = np.clip(np.sum((p - a) * ab, axis=2) / np.sum(ab * ab, axis=2), 0.0, 1.0)
    closest = a + t[..., None] * ab
    dist = np.linalg.norm(p - closest, axis=2)
    seg = np.argmin(dist, axis=1)
    rows = np.arange(p.shape[0])
    d = dist[rows, seg]
    rel = p[:, 0, :] - a[0, seg]
    cross = ab[0, seg, 0] * rel[:, 1] - ab[0, seg, 1] * rel[:, 0]
    return np.where(cross >= 0.0, d, -d)


def occupied_centers(grid: Grid) -> np.ndarray:
    ys, xs = np.nonzero(grid.occ == K_OCCUPIED)
    return np.column_stack([grid.origin[0] + (xs + 0.5) * grid.resolution,
                            grid.origin[1] + (ys + 0.5) * grid.resolution])


def clearance(points: np.ndarray, grid: Grid, radius: float, cap: float = 0.5,
              centers: np.ndarray | None = None) -> np.ndarray:
    """圆(圆心 points、半径 radius)到最近占据方块的净空,与 C++ footprint_clearance 同义。"""
    centers = occupied_centers(grid) if centers is None else centers
    half = 0.5 * grid.resolution
    out = np.empty(len(points))
    for i, (x, y) in enumerate(np.asarray(points, dtype=float)):
        near = centers[(np.abs(centers[:, 0] - x) <= radius + cap + half)
                       & (np.abs(centers[:, 1] - y) <= radius + cap + half)]
        if len(near) == 0:
            out[i] = cap
            continue
        dx = np.maximum(np.abs(x - near[:, 0]) - half, 0.0)
        dy = np.maximum(np.abs(y - near[:, 1]) - half, 0.0)
        out[i] = min(float(np.min(np.hypot(dx, dy))) - radius, cap)
    return out


def densify(polyline: np.ndarray, step: float) -> np.ndarray:
    """按弧长等距重采样折线(含两端点)。"""
    pts = [polyline[0]]
    for a, b in zip(polyline[:-1], polyline[1:]):
        n = max(1, int(math.ceil(np.linalg.norm(b - a) / step)))
        for k in range(1, n + 1):
            pts.append(a + (b - a) * k / n)
    return np.asarray(pts)


def xy_of(pose: str) -> str:
    """"x,y[,yaw]" → "x,y"(`sim plan` 只接受位置)。"""
    return ",".join(pose.split(",")[:2])


def plan_path(sim: Path, map_yaml: str, start: str, goal: str, out_csv: Path, smooth: bool = True) -> np.ndarray:
    """用 `sim plan --smooth` 和 config/nav.yaml 的 planner 段生成 sim nav 会用的同一条
    平滑路径(写到 out_csv),返回 (N, 2) 折线。smooth = False 时返回 A* 原始台阶路径。"""
    planner = read_yaml_subset(REPO / "config" / "nav.yaml")["planner"]
    planner_yaml = write_yaml_subset(planner, Path(out_csv).with_suffix(".planner.yaml"),
                                     "generated by scripts/v4 — the planner section of config/nav.yaml")
    cmd = [str(sim), "plan", "--map", str(map_yaml), "--start", xy_of(start), "--goal", xy_of(goal),
           "--config", str(planner_yaml), "--no-viz", "--out", str(out_csv)] + (["--smooth"] if smooth else [])
    Path(out_csv).parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(cmd, cwd=REPO, check=True, capture_output=True, text=True)
    df = pd.read_csv(out_csv, comment="#")
    return df[["x", "y"]].to_numpy()


# ---- 统计 -----------------------------------------------------------------------

# χ² 分位数:dof 1 / 2 的 95% 双侧区间(与 scripts/v2/analyze_ekf.py 同值)。
CHI2_95 = {1: (0.000982, 5.023886), 2: (0.050636, 7.377759)}


def chi2_quantile(p: float, dof: int) -> float:
    """χ² 分位数的 Wilson–Hilferty 近似(dof ≥ 10 时相对误差 < 1%),只用于多次运行的平均。"""
    # 只需要这几个标准正态分位数,直接查表(不为此引入 scipy)。
    z = {0.025: -1.959964, 0.975: 1.959964, 0.05: -1.644854, 0.95: 1.644854}[p]
    k = float(dof)
    return k * (1.0 - 2.0 / (9.0 * k) + z * math.sqrt(2.0 / (9.0 * k))) ** 3
