#!/usr/bin/env python3
"""
gen_floorplan.py — 从矩形清单(墙、门、家具)生成真实尺度的占据栅格地图。

输入是一个 TOML 描述文件(例如 maps/src/apartment.toml):分辨率、尺寸、外墙厚度,
以及 walls / doors / furniture 三组 [x0, y0, x1, y1] 矩形(米,原点在左下角)。
栅格化顺序:外墙 → walls(占据)→ doors(挖开)→ furniture(占据);矩形覆盖格心
落在 [x0, x1) × [y0, y1) 内的 cell。

输出 maps/<name>.pgm(P5 二进制,254 = free、0 = 占据)+ maps/<name>.yaml
(ROS map_server 约定,与 C++ map_io 和 scripts/v3/_mapio.py 兼容)。

同时按 C++ inflate() 的规则(到最近占据格心的欧氏距离 ≤ r 即占据)复算膨胀,
报告 4-连通的 free 区域数 —— A* 的 8 连通带防穿角,可达性与 4-连通等价。
权威检查在 C++ 测试(planning_tests 的 ApartmentMap.*);这里只是生成时的快速反馈。

Run:
    python scripts/v4/gen_floorplan.py maps/src/apartment.toml        # -> maps/apartment.{pgm,yaml}
    python scripts/v4/gen_floorplan.py maps/src/apartment.toml --check-inflation 0.25
"""

from __future__ import annotations

import argparse
import math
import tomllib
from collections import deque
from pathlib import Path

import numpy as np

FREE_PIXEL = 254
OCCUPIED_PIXEL = 0


def to_cells(rect: list[float], res: float, shape: tuple[int, int]) -> tuple[slice, slice]:
    """[x0, y0, x1, y1](米)→ 格心落在矩形内的 cell 范围(行 = y,列 = x)。"""
    x0, y0, x1, y1 = rect
    if not (x1 > x0 and y1 > y0):
        raise ValueError(f"degenerate rectangle {rect}")
    h, w = shape
    # 格心 (i + 0.5)·res ∈ [x0, x1) ⇔ i ∈ [ceil(x0/res − 0.5), ceil(x1/res − 0.5))
    i0 = max(0, math.ceil(x0 / res - 0.5 - 1e-9))
    i1 = min(w, math.ceil(x1 / res - 0.5 - 1e-9))
    j0 = max(0, math.ceil(y0 / res - 0.5 - 1e-9))
    j1 = min(h, math.ceil(y1 / res - 0.5 - 1e-9))
    return slice(j0, j1), slice(i0, i1)


def build_grid(spec: dict) -> np.ndarray:
    """返回占据布尔阵 occ[gy][gx](gy = 0 为最小 world y)。"""
    res = float(spec["resolution"])
    width_m, height_m = spec["size"]
    w = round(width_m / res)
    h = round(height_m / res)
    occ = np.zeros((h, w), dtype=bool)

    border = round(float(spec.get("border", 0.0)) / res)
    if border > 0:
        occ[:border, :] = occ[-border:, :] = True
        occ[:, :border] = occ[:, -border:] = True

    for group, value in (("walls", True), ("doors", False), ("furniture", True)):
        for item in spec.get(group, []):
            rows, cols = to_cells(item["rect"], res, occ.shape)
            occ[rows, cols] = value
    return occ


def inflate(occ: np.ndarray, radius_m: float, res: float) -> np.ndarray:
    """与 C++ inflate() 同一规则:到最近占据格心的距离 ≤ radius 的 cell 也占据。"""
    r = radius_m / res
    reach = math.floor(r)
    out = occ.copy()
    h, w = occ.shape
    for dy in range(-reach, reach + 1):
        for dx in range(-reach, reach + 1):
            if dx * dx + dy * dy > r * r + 1e-9:
                continue
            src = occ[max(0, -dy):h - max(0, dy), max(0, -dx):w - max(0, dx)]
            out[max(0, dy):h - max(0, -dy), max(0, dx):w - max(0, -dx)] |= src
    return out


def free_components(occ: np.ndarray) -> list[int]:
    """free cell 的 4-连通分量大小,降序。"""
    h, w = occ.shape
    seen = occ.copy()
    sizes: list[int] = []
    for sy in range(h):
        for sx in range(w):
            if seen[sy, sx]:
                continue
            seen[sy, sx] = True
            queue = deque([(sy, sx)])
            n = 0
            while queue:
                y, x = queue.popleft()
                n += 1
                for ny, nx in ((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)):
                    if 0 <= ny < h and 0 <= nx < w and not seen[ny, nx]:
                        seen[ny, nx] = True
                        queue.append((ny, nx))
            sizes.append(n)
    return sorted(sizes, reverse=True)


def write_map(occ: np.ndarray, spec: dict, name: str, source: Path, out_dir: Path) -> tuple[Path, Path]:
    pgm = out_dir / f"{name}.pgm"
    yaml = out_dir / f"{name}.yaml"
    img = np.where(occ, OCCUPIED_PIXEL, FREE_PIXEL).astype(np.uint8)[::-1]  # 图像首行 = 最大 y
    h, w = occ.shape
    header = f"P5\n# {name} generated by scripts/v4/gen_floorplan.py from {source.as_posix()}\n{w} {h}\n255\n"
    with pgm.open("wb") as f:
        f.write(header.encode("ascii"))
        f.write(img.tobytes())
    res = float(spec["resolution"])
    width_m, height_m = spec["size"]
    yaml.write_text(
        f"# {name} — 真实尺度平面图(由 scripts/v4/gen_floorplan.py 从 {source.as_posix()} 生成)。\n"
        f"# {width_m:g} x {height_m:g} m,{w}x{h} cell。P5 二进制 PGM。\n"
        f"image: {name}.pgm\n"
        f"resolution: {res:g}\n"
        "origin: [0.0, 0.0, 0.0]\n"
        "occupied_thresh: 0.65\n"
        "free_thresh: 0.25\n"
        "negate: 0\n",
        encoding="utf-8",
    )
    return pgm, yaml


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("spec", type=Path, help="floor-plan description (TOML)")
    ap.add_argument("--out-dir", type=Path, default=Path("maps"))
    ap.add_argument("--name", help="map name (default: spec file stem)")
    ap.add_argument("--check-inflation", type=float, default=0.25, metavar="R",
                    help="report free-space connectivity after inflating by R meters (default 0.25)")
    args = ap.parse_args()

    spec = tomllib.loads(args.spec.read_text(encoding="utf-8"))
    name = args.name or args.spec.stem
    occ = build_grid(spec)
    pgm, yaml = write_map(occ, spec, name, args.spec, args.out_dir)

    res = float(spec["resolution"])
    h, w = occ.shape
    print(f"{name}: {w}x{h} cells @ {res:g} m = {w * res:g} x {h * res:g} m, "
          f"free {100.0 * (~occ).mean():.1f}%")
    print(f"  wrote {pgm} and {yaml}")

    inflated = inflate(occ, args.check_inflation, res)
    sizes = free_components(inflated)
    verdict = "connected" if len(sizes) == 1 else f"NOT connected ({len(sizes)} regions: {sizes[:5]})"
    print(f"  inflation {args.check_inflation:g} m: free {100.0 * (~inflated).mean():.1f}%, {verdict}")
    if len(sizes) != 1:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
