#!/usr/bin/env python3
"""
gen_office500.py — 程序化生成一张复杂的 500×500 "楼宇平面" 测试地图。

500×500 @ 0.05 m/cell = 25m × 25m,远大于手画的 office(2×1.5m)。布局:
  - 外墙封闭;内部 6×6 = 36 个房间,房间之间是厚墙。
  - 每道隔墙在每个房间段开一个门洞 → 相邻房间皆连通(房间图连通,必有解)。
  - 每个房间内撒若干随机柱子(矩形障碍),制造房内绕行。
  - start(左下角房间)与 goal(右上角房间)各清出一块 free 区,保证起止可走。

确定性:固定 numpy 种子,产出可复现。写 P5(二进制 PGM,~250KB,远小于
同尺寸 P2 ASCII 的 ~1MB);C++ map_io 与 scripts/v3/_mapio.py 均支持 P5。

Run:
    python scripts/v3/gen_office500.py            # -> maps/office500.{pgm,yaml}
    python scripts/v3/gen_office500.py --print-startgoal
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

N = 500
RES = 0.05
ROOMS = 6
WALL_T = 3          # 墙厚(cell)
DOOR = 22           # 门洞宽(cell)
SEED = 20260625


def build_grid() -> np.ndarray:
    """返回 grid[gy][gx] 占据布尔阵(gy=0 为底,world 最小 y)。"""
    rng = np.random.default_rng(SEED)
    occ = np.zeros((N, N), dtype=bool)

    # 外墙
    occ[:WALL_T, :] = occ[-WALL_T:, :] = True
    occ[:, :WALL_T] = occ[:, -WALL_T:] = True

    step = N // ROOMS  # 房间间距
    wall_lines = [i * step for i in range(1, ROOMS)]

    # 内部隔墙(竖 + 横),厚 WALL_T
    for x in wall_lines:
        occ[:, x : x + WALL_T] = True
    for y in wall_lines:
        occ[y : y + WALL_T, :] = True

    def punch_v(x: int, seg_lo: int, seg_hi: int) -> None:  # 竖墙开门(沿 y 段)
        gc = (seg_lo + seg_hi) // 2 + int(rng.integers(-25, 26))
        occ[gc - DOOR // 2 : gc + DOOR // 2, x : x + WALL_T] = False

    def punch_h(y: int, seg_lo: int, seg_hi: int) -> None:  # 横墙开门(沿 x 段)
        gc = (seg_lo + seg_hi) // 2 + int(rng.integers(-25, 26))
        occ[y : y + WALL_T, gc - DOOR // 2 : gc + DOOR // 2] = False

    # 每道墙在每个房间段开一个门洞 → 相邻房间全连通
    for x in wall_lines:
        for r in range(ROOMS):
            punch_v(x, r * step, (r + 1) * step)
    for y in wall_lines:
        for c in range(ROOMS):
            punch_h(y, c * step, (c + 1) * step)

    # 房内随机柱子(避开房门附近,留边距)
    for r in range(ROOMS):
        for c in range(ROOMS):
            y0, y1 = r * step + WALL_T, (r + 1) * step - WALL_T
            x0, x1 = c * step + WALL_T, (c + 1) * step - WALL_T
            for _ in range(int(rng.integers(2, 5))):
                pw, ph = int(rng.integers(10, 28)), int(rng.integers(10, 28))
                if x1 - pw - 12 <= x0 + 12 or y1 - ph - 12 <= y0 + 12:
                    continue
                px = int(rng.integers(x0 + 12, x1 - pw - 12))
                py = int(rng.integers(y0 + 12, y1 - ph - 12))
                occ[py : py + ph, px : px + pw] = True

    # 清出 start / goal 自由区(左下房间 / 右上房间中心附近)
    occ[WALL_T + 5 : WALL_T + 35, WALL_T + 5 : WALL_T + 35] = False
    occ[N - WALL_T - 35 : N - WALL_T - 5, N - WALL_T - 35 : N - WALL_T - 5] = False
    return occ


def write_p5(occ: np.ndarray, pgm: Path) -> None:
    """写 P5 二进制 PGM。grid[gy] → 图像行序自上而下(顶行 = 最大 gy),需 y 翻转。"""
    img = np.where(occ, 0, 255).astype(np.uint8)
    img = img[::-1]  # gy=N-1 在图像第一行(顶)
    header = f"P5\n# office500 generated by scripts/v3/gen_office500.py (seed={SEED})\n{N} {N}\n255\n"
    with open(pgm, "wb") as f:
        f.write(header.encode("ascii"))
        f.write(img.tobytes())


def startgoal() -> tuple[str, str]:
    # 左下/右上自由区内的 world 坐标(cell 中心)。
    s = (WALL_T + 20 + 0.5) * RES
    g = (N - WALL_T - 20 + 0.5) * RES
    return f"{s:.3f},{s:.3f}", f"{g:.3f},{g:.3f}"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path, default=Path("maps"))
    ap.add_argument("--print-startgoal", action="store_true")
    args = ap.parse_args()

    if args.print_startgoal:
        s, g = startgoal()
        print(f"start={s} goal={g}")
        return

    args.out_dir.mkdir(parents=True, exist_ok=True)
    occ = build_grid()
    pgm = args.out_dir / "office500.pgm"
    yaml = args.out_dir / "office500.yaml"
    write_p5(occ, pgm)
    yaml.write_text(
        "# office500 — 程序化 500x500 楼宇平面(由 scripts/v3/gen_office500.py 生成)。\n"
        "# 25x25m,6x6 房间 + 门洞 + 柱子。P5 二进制 PGM。\n"
        f"image: office500.pgm\nresolution: {RES}\norigin: [0.0, 0.0, 0.0]\n"
        "occupied_thresh: 0.65\nfree_thresh: 0.25\nnegate: 0\n"
    )
    s, g = startgoal()
    occ_frac = occ.mean()
    print(f"wrote {pgm} ({pgm.stat().st_size} bytes) and {yaml}")
    print(f"  {N}x{N} @ {RES}m, occupied fraction = {occ_frac:.3f}")
    print(f"  suggested: --start {s} --goal {g}")


if __name__ == "__main__":
    main()
